refcoco_train_file: ['data/refcoco_train.json',]
refcoco_val_file: ['data/refcoco_val.json']
refcoco_testA: ['data/refcoco_testA.json']
refcoco_testB: ['data/refcoco_testB.json']
refcocog_train_file: ['data/refcocog_train.json',]
refcocog_val: ['data/refcocog_val.json']
refcocog_test: ['data/refcocog_test.json']
refcocop_train_file: ['data/refcocop_train.json',]
refcocop_val: ['data/refcocop_val.json']
refcocop_testA: ['data/refcoco_testA.json']
refcocop_testB: ['data/refcocop_testB.json']
flickr_train_file: ['data/flickr_single_bbox_train.json',]
flcikr_val: ['data/flickr_single_bbox_val.json']
flcikr_test: ['data/flickr_single_bbox_test.json']

alpha: 0.4
temp: 0.07
batch_size: 8
bert_config: 'configs/config_bert.json'
embed_dim: 256
exp_decay_ratio: 0.15
image_res: 512
mlm_probability: 0.15
momentum: 0.995
pos_token_mask_type: 1
postoken_temp: 2
pseudo_normal_ratio: 1
queue_size: 65536
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}


